### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by 55645nato** [Eltion/Kissanime-Downloader#12]
I have been using this for a while and I really appreciate it, but it suddenly doesn't work. I've tried it on 2 different computers and on 2 different browsers. On the computer I used to use it begins to try to construct an HTML list (I always used HTML) but can't find the first one. On my other computer, it doesn't even show up as if the script was installed.

**Comment by 55645nato** [comment]
It works again. Thanks.

**Comment by badbones69** [comment]
Please close this since its fixed.
