### ISSUE TITLE
Script removed by greasyfork, and my pc (against my will)

### ISSUE THREAD

**Issue by argonatron** [Eltion/Kissanime-Downloader#16]
see title. this happened about 3-4 weeks ago and as of yet i have to been able to find a way to fix this.

**Comment by badbones69** [comment]
I have had this issue also. I am not sure how to fix it for FireFox at this time but chrome is an easy fix.

## Chrome:
### 1. 
Go into the TamperMonkey's DashBoard.
![](https://image.ibb.co/e8kzKo/image.png)

### 2. 
Delete the old KissAnime Downloader.
![](https://image.ibb.co/dCTrX8/image.png)

### 3.
Then go to the KissAnime Multi Downloader.user.js file.
Current version as of this post: [KissAnime Multi Downloader.user.js v3.3.1](https://github.com/Eltion/Kissanime-Downloader/blob/2ed1f250b8b1bce0d8cf50a9a358028db341389c/KissAnime%20Multi%20Downloader.user.js)
Newest version if reading later on: [KissAnime Multi Downloader.user.js](https://github.com/Eltion/Kissanime-Downloader/blob/master/KissAnime%20Multi%20Downloader.user.js)

### 4.
Click the "Raw" button and it should open TamperMonkey's install page automatically.
![](https://image.ibb.co/kMrgzo/image.png)

### 5.
Hit install to install the new version.
![](https://image.ibb.co/jSvVs8/image.png)

### 6.
Go back to the DashBoard of TamperMonkey and refresh the page and it should show the newest version.

### 7.
Go to KissAnime and it should load the page now.

## Versions:
Chrome: 67
TamperMonkey: 4.6
KissAnime Downloader: 3.1.1

**Comment by argonatron** [comment]
That worked perfectly. Thanks friend.

**Comment by badbones69** [comment]
No problem, make sure to close this since its fixed.
