### ISSUE TITLE
Doesn't work in Chrome Browser

### ISSUE THREAD

**Issue by spyderbibek** [Eltion/Kissanime-Downloader#2]
Error shown in the attached image occurs when try to use the script in Chrome..
![aaaaaa](https://user-images.githubusercontent.com/9642701/28904517-441638ae-782b-11e7-85e7-c082267033e3.PNG)

**Comment by tuhintarafder6** [comment]
Same here..
I tried with [this](http://kissanime.ru/Anime/Pokemon-Black-White-Dub) link

**Comment by Eltion** [comment]
Problem fixed on 2.3 version.
